/*
 * Timer_0_configuration.h
 *
 *  Created on: ???/???/????
 *      Author: dell
 */

#ifndef MCAL_TIMER_0_TIMER_0_CONFIGURATION_H_
#define MCAL_TIMER_0_TIMER_0_CONFIGURATION_H_
/*
 * choose from:
 *   TIMER0_PRESCALER_1
 *   TIMER0_PRESCALER_8
 *   TIMER0_PRESCALER_64
 *   TIMER0_PRESCALER_256
 *   TIMER0_PRESCALER_1024
 *   TIMER0_PRESCALER_EXTCLK_FALLEDGE
 *   TIMER0_PRESCALER_EXTCLK_RAISEDGE
 */
#define TIMER_0_PRESCALER     TIMER0_PRESCALER_256

/*
 *   choose from :
 *   TIMER0_NORMAL_MODE
 *   TIMER0_CTC_MODE
 *   TIMER0_PHASECORRECT_MODE
 *   TIMER0_FASTPWM_MODE
 *
 */
#define TIMER_0_MODE  TIMER0_FASTPWM_MODE

/*
 * choose from :
 *  Non PWM:
 *   TIMER0_OC0_DISCONNECTED
 *   TIMER0_OC0_TOG
 *   TIMER0_OC0_CLEAR
 *   TIMER0_OC0_SET
 *   TIMER_OC0_PWM_NON_INVERTING
 *   TIMER_OC0_PWM_INVERTING
 */
#define TIMER_0_OC0_MODE  TIMER_OC0_PWM_NON_INVERTING
/*
 * select F_OSC
 */
#define F_OSC                  16
#endif /* MCAL_TIMER_0_TIMER_0_CONFIGURATION_H_ */
