/*
 * Timer2_config.h
 *
 *  Created on: Aug 31, 2022
 *      Author: Samy
 */

#ifndef TIMER2_TIMER2_CONFIG_H_
#define TIMER2_TIMER2_CONFIG_H_


/*
 * choose from :
 * TIMER2_PRESCALAR_1
 * TIMER2_PRESCALAR_8
 * TIMER2_PRESCALAR_32
 * TIMER2_PRESCALAR_64
 * TIMER2_PRESCALAR_128
 * TIMER2_PRESCALAR_256
 * TIMER2_PRESCALAR_1024
 */
#define TIMER_2_PRESCALER		TIMER2_PRESCALAR_256

/*
 * choose from :
 * TIMER2_NORMAL_MODE
 * TIMER2_CTC_MODE
 * TIMER2_PHASECORRECT_MODE
 * TIMER2_FASTPWM_MODE
 */
#define TIMER_2_MODE			  TIMER2_CTC_MODE


/*
 * choose from:
 * Non PWM:
 * TIMER2_OC2_DISCONNECTED
 * TIMER2_OC2_TOG
 * TIMER2_OC2_CLR
 * TIMER2_OC2_SET
 * PWM:
 * TIMER2_FASTPWM_MODE
 * TIMER2_OC2_PWM_INVERTING
 */
#define TIMER_2_OC2_MODE		TIMER2_OC2_DISCONNECTED

#define F_OSC					16	// MHZ


#endif /* TIMER2_TIMER2_CONFIG_H_ */
