/*
 * Ext_Int_configuration.h
 *
 *  Created on: ???/???/????
 *      Author: dell
 */

#ifndef MCAL_EXT_INT_EXT_INT_CONFIGURATION_H_
#define MCAL_EXT_INT_EXT_INT_CONFIGURATION_H_
/*
 *    SELECT EXT_INT0_SENSE_CONTROL : FALLING_EDGE , RISING_EDGE , LOW_LEVEL , LOGICAL_CHANGE
 */
#define EXT_INT0_SENSE_CONTROL         FALLING_EDGE
/*
 *    SELECT EXT_INT1_SENSE_CONTROL : FALLING_EDGE , RISING_EDGE , LOW_LEVEL , LOGICAL_CHANGE
 */
#define EXT_INT1_SENSE_CONTROL         FALLING_EDGE
/*
 *    SELECT EXT_INT2_SENSE_CONTROL : FALLING_EDGE , RISING_EDGE
 */
#define EXT_INT2_SENSE_CONTROL         FALLING_EDGE


#endif /* MCAL_EXT_INT_EXT_INT_CONFIGURATION_H_ */
